apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: presentations-test
  namespace: argocd
spec:
  project: presentations
  source:
    repoURL: https://github.com/ryanrolds/presentations.git
    targetRevision: master
    helm:
      parameters:
        - name: ingress
          value: presentations-test
    path: ./chart/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: presentations-test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true