apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: presentations
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: presentations
    server: https://kubernetes.default.svc
  - name: in-cluster
    namespace: presentations-test
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/ryanrolds/presentations.git