---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentations
  labels:
    app: presentations
spec:
  selector:
    matchLabels:
      app: presentations
  replicas: 1
  template:
    metadata:
      labels:
        app: presentations
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: presentations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
