on:
  push:
    branches:
    - production
jobs:
  build_and_deploy_prod:
    name: Build & Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Build HTML
        run: make all

      - name: Build presentation image
        run: docker build .

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.pedanticorderliness.com
          username: ${{ secrets.DOCKER_REG_USER }}
          password: ${{ secrets.DOCKER_REG_PASS }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          tags: |
            docker.pedanticorderliness.com/presentations:${{ github.sha }}
          push: true

      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.PO_APP_ID }}
          private_key: ${{ secrets.PO_PRIVATE_KEY }}

      - name: Update image tag
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh workflow run image_update.yaml \
            -R ryanrolds/infrastructure \
            -r production \
            -F chart=presentations \
            -F values_file=production.yaml \
            -F tag_path=image.tag \
            -F tag=${{ github.sha }} \
            -F branch=production
